language: node_js
node_js: stable

script:
- yarn run test:ci

jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - yarn
      - yarn run build
      deploy:
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          tags: true
