dist: precise
language: node_js
node_js: stable

before_script: npm install
script: npm run test:ci

jobs:
  include:
    - stage: npm release
      node_js: stable
      before_deploy:
      - npm install
      - npm run build:ci
      deploy:
        provider: npm
        email: "webdev@experium.ru"
        api_key: $NPM_API_KEY
        on:
          tags: true
